package-lock.json
package.json
src/utils/validation-types.js

https://github.com/open-cluster-management/backlog/issues/7503
- should allow / and .

allow github allowed symbols

---

package-lock.json
package.json
src/components/YamlEditor.js
src/utils/validation-types.js

open-cluster-management/backlog#6900

Scroll fix

---

package-lock.json
package.json
src/scss/control-panel.scss

https://github.com/open-cluster-management/backlog/issues/7116
With the fix:

fix ui problem and inc version

---

package-lock.json
package.json
src/TemplateEditor.js

fixes: open-cluster-management/backlog#10597

fix 2nd tab edit bug

---

package-lock.json
package.json
src/TemplateEditor.js
src/utils/refresh-source-from-stack.js

open-cluster-management/backlog#10597 for 2.3

fix edit bug

---

package-lock.json
package.json
src/utils/refresh-source-from-stack.js

open-cluster-management/backlog#10597 for 2.2

fix bug in 22

---

CONTRIBUTING.md
README.md
package-lock.json
package.json
src/utils/validation-types.js

Signed-off-by: Chris Ahl <cahl@redhat.com>
For issue https://github.com/open-cluster-management/backlog/issues/12204

add validation for IP address that is optional

---

package-lock.json
package.json
src/controls/ControlPanelComboBox.js
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap

`simplified` function should be optional.

Fix ComboBox

---

package.json
src/controls/ControlPanel.js

Signed-off-by: Valentina Birsan <vbirsan@redhat.com>
https://github.com/open-cluster-management/backlog/issues/12443

fix combobox losing focus on invalid input

---

package-lock.json
package.json
src/controls/ControlPanel.js
src/controls/ControlPanelFinish.js
src/utils/logger.js

misc fixes

---

package-lock.json
package.json
src/TemplateEditor.js

check for resizeobserver

---

package-lock.json
package.json
src/controls/ControlPanel.js

support hidden on step or section

---

package-lock.json
package.json
src/controls/ControlPanelComboBox.js
src/controls/ControlPanelMultiSelect.js
src/controls/ControlPanelSingleSelect.js
src/scss/control-panel.scss

combo box bugs

---

package-lock.json
package.json
src/TemplateEditor.js
src/controls/ControlPanelComboBox.js
src/scss/template-editor.scss
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap

fix combo box

---

package-lock.json
package.json
src/controls/ControlPanel.js
src/controls/ControlPanelComboBox.js
src/controls/ControlPanelTreeSelect.js
src/scss/control-panel.scss
src/utils/refresh-source-from-templates.js
src/utils/source-utils.js
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
tests/jest/components/TemplateEditor/controls/__snapshots__/ControlPanelTreeSelect.test.js.snap

combo bugs

---

package-lock.json
package.json
src/controls/ControlPanelComboBox.js
src/controls/ControlPanelFormGroup.js
src/utils/source-utils.js
src/utils/validate-controls.js

read only big

---

package-lock.json
package.json
src/utils/validate-controls.js

read only bug

---

package-lock.json
package.json
src/utils/source-utils.js
src/utils/validate-controls.js

readonly bug

---

package-lock.json
package.json
src/controls/ControlPanel.js

wizard page bug

---

package-lock.json
package.json
src/controls/ControlPanel.js
src/utils/refresh-source-highlighting.js

on change fix

---

package-lock.json
package.json
src/utils/logger.js

logger exception

---

package-lock.json
package.json
src/TemplateEditor.js
src/controls/ControlPanelComboBox.js
src/controls/ControlPanelTable.js
src/utils/initialize-control-functions.js
src/utils/source-utils.js
src/utils/validate-controls.js

combo and refresh bugs

---

package-lock.json
package.json
src/TemplateEditor.js
src/components/YamlEditor.js

provide default theme

---

package-lock.json
package.json
src/TemplateEditor.js
src/utils/validate-controls.js

add custom validator

---

.travis.yml
package-lock.json
package.json
src/scss/control-panel.scss

chnage to 4.0

---

src/TemplateEditor.js
src/components/YamlEditor.js
src/controls/ControlPanel.js
src/controls/ControlPanelCards.js

- adds readonly editor mode
- adds ability to specify sections for cards component
- accepts onStepChange callback

Add functionality to be able to integrate CIM components into create cluster wizard

---

package-lock.json
package.json
src/controls/ControlPanel.js

fix couple exceptions

---

package-lock.json
package.json
src/TemplateEditor.js
src/components/EditorHeader.js
src/components/YamlEditor.js
src/scss/editor-bar.scss
src/scss/editor-header.scss
src/utils/initialize-control-data.js
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
tests/jest/components/TemplateEditor/components/__snapshots__/EditorHeader.test.js.snap
tests/jest/components/TemplateEditor/components/__snapshots__/YamlEditor.test.js.snap

readonly version

---

src/index.d.ts

Signed-off-by: James Talton <jtalton@redhat.com>

fix type definitions

---

package-lock.json
package.json
src/index.d.ts

fix type part 2

---

package-lock.json
package.json
src/controls/ControlPanelWizard.js
src/scss/control-panel-finish.scss
src/scss/control-panel.scss
src/utils/refresh-source-highlighting.js
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap

exclamation

---

package-lock.json
package.json
src/TemplateEditor.js
src/controls/ControlPanelCards.js
src/utils/validate-controls.js

fit n finish

---

package-lock.json
package.json
src/controls/ControlPanelCheckbox.js
src/controls/ControlPanelFinish.js
src/controls/ControlPanelFormGroup.js
src/controls/ControlPanelSingleSelect.js
src/controls/ControlPanelTextArea.js
src/controls/ControlPanelValues.js
src/utils/initialize-control-data.js
src/utils/logger.js
src/utils/refresh-source-from-stack.js
src/utils/refresh-source-from-templates.js
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
tests/jest/components/TemplateEditor/controls/__snapshots__/ControlPanelCheckbox.test.js.snap

disconnected

---

package-lock.json
package.json
src/controls/ControlPanelFinish.js
src/controls/ControlPanelWizard.js

fix react warnings

---

package-lock.json
package.json
src/TemplateEditor.js
src/controls/ControlPanelAccordion.js
src/utils/initialize-control-functions.js
src/utils/refresh-source-from-stack.js

exceptions

---

package-lock.json
package.json
src/scss/control-panel.scss
src/utils/refresh-source-from-stack.js

fix app ui test

---

CONTRIBUTING.md
README.md
package-lock.json
package.json

https://github.com/stolostron/backlog/issues/18716

Stolostron

---

package-lock.json
package.json
src/controls/ControlPanelAccordion.js

summarize i18n

---

package-lock.json
package.json
src/components/EditorHeader.js
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
tests/jest/components/TemplateEditor/components/__snapshots__/EditorHeader.test.js.snap

https://github.com/stolostron/backlog/issues/20794

Fix unintentional redirect

---

package-lock.json
package.json
src/components/EditorHeader.js
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap
tests/jest/components/TemplateEditor/components/__snapshots__/EditorHeader.test.js.snap

https://github.com/stolostron/backlog/issues/20794

Refix redirect

---

package-lock.json
package.json
src/controls/ControlPanelTreeSelect.js

https://github.com/stolostron/backlog/issues/20681

Clear active value like ComboBox

---

src/TemplateEditor.js

needed to fix https://bugzilla.redhat.com/show_bug.cgi?id=2070024
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

Validate form and do not allow to continue if there are errors

---

package-lock.json
package.json
src/TemplateEditor.js

Signed-off-by: Ella Juengst <ellajuengst@gmail.com>

Implementing onChange function when adding handling group change.

---

package-lock.json

Signed-off-by: Kevin Cormier <kcormier@redhat.com>

Fix package-lock.json version

---

package-lock.json
package.json
src/utils/validate-controls.js

to address: https://github.com/stolostron/backlog/issues/20067
Signed-off-by: Ella Juengst <ellajuengst@gmail.com>

Single select validation fix

---

package-lock.json
package.json
src/controls/ControlPanelTextInput.js

issue 214655 -2.4

---

package-lock.json
package.json
src/utils/refresh-source-from-stack.js

Issue22136 2.4 1

---

package-lock.json
package.json
src/utils/validate-controls.js

Make sure all callers of addExceptions pass all args
https://github.com/stolostron/backlog/issues/22518

Avoid breakage when no link exists in YAML

---

src/utils/refresh-source-from-templates.js

https://github.com/stolostron/temptifly/pull/175 broke AI wizards

Do not encode undefined values

---

src/controls/ControlPanel.js
src/controls/ControlPanelFinish.js
src/controls/ControlPanelWizard.js
src/css/control-panel-controls.css
src/css/template-editor.css
tests/jest/components/TemplateEditor/__snapshots__/TemplateEditor.test.js.snap

- it is not expected anymore that the temptifly wizards are wrapped by pf-c-content
- fix css rules which break custom components styling
ACM console update https://github.com/stolostron/console/pull/1701

Update styling of the components

---

package-lock.json
package.json
src/TemplateEditor.js
src/utils/refresh-source-from-stack.js
src/utils/refresh-source-from-templates.js
src/utils/source-utils.js

fix immutable bugs

---

package-lock.json
package.json
src/controls/ControlPanelComboBox.js

fix on combo
